### ISSUE TITLE
Move task flow analysis to Interpretation

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#24]
I probably assumed this was an "analysis" activity, but upon further review, it's actually more of a system design mapping activity based on user research/observation. So it probably belongs in the Interpretation category and maybe needs to be renamed as well. (Intermediate step before journey map, user flows for interaction design.)

**Comment by pglevy** [comment]
A brief investigation into the terminology indicates this is more complicated that I originally, but I think I have a recommendation for moving forward.

Resources:
- This is a [helpful article](https://blog.prototypr.io/ux-flows-and-why-theyre-so-confusing-26670b9089d4) that discusses the various terms and why it gets confusing. 

Thoughts:
- "Task analysis" is a way to describing "what people do." I think the discovery of this information is implied and embedded within the other activities that we carry out in Awareness and Observation, such as interviews, contextual inquiry, etc.
- What is probably more useful for our purposes is to describe the output/artifact from our various analysis activities in a way that can help the team visualize what people go through to accomplish and what we can do to make it better.
- I find myself aligned with the thinking expressed by Alexey Kolchenko in [this conversation](https://ux.stackexchange.com/questions/45405/what-are-the-differences-between-user-flows-task-flows-and-workflows): task flow and user flow are interchangeable in practical use, and since we are UX designers generally focused on the user perspective, the term "user flow" is a better term for us.
- Flowmapp (the tool we may end up using regularly for this method) describes their feature as "User Flow" and define it this way: "User Flow is the logic path taken by users on a website or app to achieve goals. The User Flow lead them from entry point through set of steps towards a successful final action, such as purchasing a product." I think this is pretty consistent with most of the language that is current in the Task Analysis method.

to be continued...

**Comment by pglevy** [comment]
Here is a [draft of the text on a new branch](https://github.com/Bixal/methods/blob/rename-task-flow-analysis/_methods/task-flow-analysis.md). I made some minor tweaks so it was consistent with how it referred "analysis" and "diagram." 

Here's a screenshot of it running locally...
![image](https://user-images.githubusercontent.com/5177337/101410734-c75a1780-38ad-11eb-8f0b-c61b41a1dba3.png)

**Comment by pglevy** [comment]
Any final thoughts on this one before I close it out, @Bixal/methods ?

**Comment by allie-shaw** [comment]
This looks good too. Thanks @pglevy !

**Comment by sofya-UX** [comment]
Looks good to me as well  @pglevy
