### ISSUE TITLE
Remove "cartography" article from Journey Mapping method resources

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#33]
May work for a new Concept Mapping method.

## Acceptance Criteria
- “Designing Digital Strategies, Part 1: Cartography.” does not appear.
- Journey Mapping 101 article does appear.
- Link goes to page on NNG site.

**Comment by pglevy** [comment]
Add this one instead: https://www.nngroup.com/articles/journey-mapping-101/

**Comment by allie-shaw** [comment]
@pglevy Looks good to me!
cc: @sofya-UX

**Comment by pglevy** [comment]
Thanks for the quick reply, @allie-shaw. And we're live!
