### ISSUE TITLE
Update social card

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#41]
So it doesn't look like this when sharing links...
![image](https://user-images.githubusercontent.com/5177337/93522956-44ee3700-f900-11ea-960d-5e689a36ddab.png)

**Comment by pglevy** [comment]
Using https://metatags.io/, previews for Google search, Facebook, and Twitter
![image](https://user-images.githubusercontent.com/5177337/100553569-871ae980-325c-11eb-9449-5bc8b2c26de8.png)

![image](https://user-images.githubusercontent.com/5177337/100553587-a7e33f00-325c-11eb-8be3-57b335fc2e13.png)

**Comment by pglevy** [comment]
Not going to open PR because this is already live, but can one of you confirm this is working on a Facebook post? You don't have to send it, just paste a link into post draft and see if the preview appears similar to screenshots above. @allie-shaw @sofya-UX

**Comment by sofya-UX** [comment]
@pglevy let me dust off my FB login (have been abandoning this platform for ethical reasons BC dark UX patterns for a few years now)

**Comment by pglevy** [comment]
don't feel obligated @sofya-UX!

**Comment by sofya-UX** [comment]
@pglevy works on my end! 
<img width="517" alt="Screen Shot 2020-11-30 at 5 15 51 PM" src="https://user-images.githubusercontent.com/60902508/100672442-f0b7f800-332f-11eb-9111-6a5fceccb4b7.png">

**Comment by pglevy** [comment]
Cool, thanks @sofya-UX. I'll post the Twitter Card Validator screen shot here as well, and we'll call this one done.

![image](https://user-images.githubusercontent.com/5177337/100672990-b1d67200-3330-11eb-9bf2-60ecd00595fe.png)
