### ISSUE TITLE
Draft a working agreement outline

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#49]
See https://github.com/Bixal/methods/blob/master/PRODUCT_TEAM.md for some inspiration from the 18F version.

**Comment by pglevy** [comment]
@sofya-UX , have you had a chance to look at this yet?

**Comment by sofya-UX** [comment]
@pglevy thanks for pinging me, taking a stab at it right it today. Do you see it as a new page in Wiki's menu? or in the body of Wiki?

**Comment by pglevy** [comment]
Eventually we'll get it into the wiki, but it can start anywhere you're comfortable for now.

**Comment by pglevy** [comment]
@sofya-UX , were you able to start something for this yet? If not, I can take a first pass. I do want to leave time for us to start discussing some actual work we want to commit to for the next cycle. (Current cycle ends 11/20.)

**Comment by sofya-UX** [comment]
@pglevy I just published my first draft of the working agreement, and would love your input/feedback/comments on how to make it better

**Comment by pglevy** [comment]
Cool, thanks! I'll take a look and we'll go from there.

**Comment by pglevy** [comment]
Thanks for getting this going, @sofya-UX. As I look back on it (and the example from 18F), I realize I'm seeing this as more of an outline for a working agreement. It sort of defines the things we need to define. But the WA itself needs to get into more of the specifics. I think a good next step is to set up [something like this WA activity](https://www.atlassian.com/team-playbook/plays/working-agreements) to add more detail. I'll take what you've started and get a board going.

**Comment by pglevy** [comment]
Here's a [start](https://miro.com/app/board/o9J_lf8S0Pg=/).

**Comment by pglevy** [comment]
Going with [this page in the wiki](https://github.com/Bixal/methods/wiki/Bixal-Methods-team-working-agreement) as an initial outline for now. Continuing work as a shaping activity in Cycle 2 (#62).
