### ISSUE TITLE
Refine working agreement

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#62]
Build on the outline we started in cycle 1 to further discuss and capture the working conventions for this product team. Continue work and discussion started in #49.

**Comment by pglevy** [comment]
@sofya-UX and @allie-shaw , I'm re-reading Lean UX, and they mention this as an example of a [working agreement](https://medium.com/@giffco/getting-tactical-product-team-working-agreements-b26aa46255ba) they like. ([Template](https://docs.google.com/spreadsheets/d/1EYkSwnKVh_Y9207c_2FYSILXA6U-vUVq73hHmIe-yT0/edit#gid=0)). Maybe this could work as an outline to build on.

**Comment by sofya-UX** [comment]
Reviewing the materials that @pglevy shared today. I spun up a version of the template and started customizing it and also capturing questions as I go.

**Comment by pglevy** [comment]
Some other references:
https://tech.gsa.gov/guides/agile_team_working_agreement/
https://34slpa7u66f159hfp1fhl9aur1-wpengine.netdna-ssl.com/wp-content/uploads/2018/10/Working-Agreement-Canvas-v1.24.pdf
https://derisking-guide.18f.gov/qasp/
