### ISSUE TITLE
Conduct template inventory of current site

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#64]
Determine what templates we currently have referenced in the site.

## Acceptance criteria
- [x] List of internal templates (documents or pages within site)
- [x] List of external templates (external resources like websites or documents)

**Comment by pglevy** [comment]
@allie-shaw, are you still working on compiling, or would you say it's "ready for review"?

**Comment by allie-shaw** [comment]
In progress:
https://github.com/Bixal/methods/wiki/Template-Inventory

**Comment by allie-shaw** [comment]
Completed:
https://github.com/Bixal/methods/wiki/Template-Inventory

**Comment by pglevy** [comment]
Awesome. Thanks, @allie-shaw! I think I finally fixed those 404 errors.
