### ISSUE TITLE
Conduct inventory of relevant Miro templates

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#65]
Let's figure what Miro has available out of the box that can be easily applied to existing Methods. Maybe create a separate Miro "project" to compile these.

## Acceptance criteria
- [ ] list of links to Miro templates that map to current Methods

**Comment by sofya-UX** [comment]
Added the "Miro templates audit" page to Wiki. Added links to Miro templates. Need to edit formatting on the page. 
But the content is ready for review @Bixal/methods

**Comment by pglevy** [comment]
This looks great, @sofya-UX! I noticed the Miroverse links aren't working. Maybe they updated their URL structure? Do you mind double checking that?

**Comment by sofya-UX** [comment]
Thanks for flagging this @pglevy. I went in and cleaned up those links, they work on my end. Please, let me know if the issue persists on your end: https://github.com/Bixal/methods/wiki/Miro-Templates-Audit
