### ISSUE TITLE
Add method for "web page quality audit"

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#66]
This is a lightweight discovery activity that can surface easy fixes early in the project. It uses an extension built into Chrome. [More details here](https://developers.google.com/web/tools/lighthouse).

## Acceptance criteria
- [ ] Includes all user-facing content:
  - [ ] title
  - [ ] what
  - [ ] why
  - [ ] how
  - [ ] phase
  - [ ] time required
  - [ ] resources
  - [ ] considerations
- [ ] Includes additional front matter content as needed.
- [ ] Considers input from members of the UX team.
- [ ] Includes consideration for specific tools and templates.
- [ ] Includes consideration for how to conduct with widely available tools.
- [ ] Follow [plain language guidelines](https://accessibility.digital.gov/content-design/plain-language/), including checking against the [plainlanguage.gov list for web](https://www.plainlanguage.gov/resources/checklists/web-checklist/).

## Resources to consider
- [Google Lighthouse](https://developers.google.com/web/tools/lighthouse)

**Comment by pglevy** [comment]
Started a first draft of this method. It's on a [separate branch here](https://github.com/Bixal/methods/blob/page-quality-audit/_methods/page-quality-audit.md). I don't want to influence how we share feedback at this point, so if you want to copy the text into a Word doc or something else, feel free. You could also just add comments or make your own copy on a new branch — whatever works. For a simple, browser-based Markdown editor, you could also try https://stackedit.io/. 

Including some screenshots of it running locally... @allie-shaw @sofya-UX 

![image](https://user-images.githubusercontent.com/5177337/100769779-843e0700-33ca-11eb-9929-a4c19b3a1690.png)

![image](https://user-images.githubusercontent.com/5177337/100769825-928c2300-33ca-11eb-8682-f41486a529e6.png)

**Comment by pglevy** [comment]
@Bixal/methods, I might regret this, but I created a copy of the main repo (a fork), so that we can "stage" new methods on a live site without affecting the main site. So you can [check out the Page Quality Audit here](https://pglevy.github.io/methods-staging/awareness/page-quality-audit/), and leave feedback in this issue. With this approach, I won't create a pull request yet, but we can review and give feedback based on how it looks/works on a real site. Let me know what you think.

**Comment by pglevy** [comment]
Any final thoughts on this one before I close it out, @Bixal/methods ?

**Comment by sofya-UX** [comment]
@pglevy this looks good, thank you!

**Comment by allie-shaw** [comment]
@pglevy  none from me either.
