### ISSUE TITLE
Create researcher introduction message

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#81]
[Example from 18F UX Guide](https://github.com/18F/ux-guide/blob/master/_pages/resources/email-templates/researcher-introduces-themselves.md)

**Comment by katharine-carr** [comment]
Working on this and this landed in my inbox the other day.

![Screen Shot 2021-01-28 at 11 05 33 AM](https://user-images.githubusercontent.com/50249974/106296782-14a89480-6220-11eb-87ae-41c1568b3194.png)

"You will be incentivized with a $15 gift card" cracked me up.

**Comment by katharine-carr** [comment]
Hey @pglevy and @sofya-UX - here is what I have for the researcher intro/recruitment message for your eyes. You can also see my working file (easier on the eyes if you ask me)[ here](https://paper.dropbox.com/doc/Create-researcher-introduction-message-81--BEhPQdFgLxMztVJrRwVw6g4KAQ-2UJkLsR6SDZPnktEXiAp8).

### Guidelines

- Give the participant relevant context of what you are doing - are you on a team, working alone? What agency are you working with? What’s the goal of the project? Think in terms of how the project would help this person, and the type of information you are seeking from them.
- Avoid using the term ‘research’ as this can have a different connotation to audiences not in the UX research field. Instead, try ‘running a study’, ‘gathering information’ or ‘seeking to learn’.
- If relevant, share the name of referring party near the beginning of the email, or in the subject line as well.
- Give a date range or time frame that you’d like to do the interview in.
- Be clear about what the method is and the time investment on the participant’s side. Is it a survey that takes ten minutes? Is it an interview that lasts about an hour?
- Include information about technology expectations - remote vs in person, screen-sharing component, what tool you’ll use to connect. 
- Format the ask in a different type to draw the eye (bold, italics, etc.)
- Leave the ending open so they can ask further questions before accepting.
- Do not use acronyms the participant might not be familiar with, or more jargon than necessary.


### Template: With Referral

Hi [Participant name],

[Referral name] shared your contact information with me. I’m part of a team working with [agency] to [achieve some goal relevant to the participant], and he mentioned you as someone who might be able to give us some feedback. We’re [performing some research method] with [audience group] to [achieve the goal of the research method].

**Would you have [amount of time] to [participate in some research method] over [some time period]?** [Any additional technical requirements to participating]

I’m happy to answer further questions or schedule a time with you. Let me know if you’re interested.

Best,
[Your Name]

**Example:**
Hi Frodo,

Bilbo Baggins shared your contact information with me. I’m part of a team working with the Department of Education to improve public hobbit education, and he mentioned you as someone who might be able to give us some feedback. We’re doing a series of interviews with hobbit students to hear their experiences and learn where improvements are needed. 

**Would you have about an hour to have a conversation with us over the next week?** The interview would be remote, through Microsoft Teams and have a screen-sharing component.

I’m happy to answer further questions or schedule a time with you. Let me know if you’d be interested.

Best,
Samwise


### Template: No Referral

I’m part of a team working with [agency] to [achieve some goal relevant to the participant]. We’re [performing some research method] with [audience group] to [achieve the goal of the research method].

Would you have [amount of time] to [participate in some research method] over [some time period]? [Any additional technical requirements to participating]

I’m happy to answer further questions or schedule a time with you. Let me know if you’re interested.

Best,
[Your name]

**Example:**
Hi Frodo,

I’m part of a team working with the Department of Education to improve public hobbit education. We’re doing a series of interviews with hobbit students to hear their experiences and learn where improvements are needed. 

**Would you have about an hour to have a conversation with us over the next week?** The interview would be remote, through Microsoft Teams and have a screen-sharing component.

I’m happy to answer further questions or schedule a time with you. Let me know if you’d be interested.

Best,
Samwise

**Comment by sofya-UX** [comment]
Hey @katharine-carr nice work! I was cracking up at the name choice in the examples, you are so creative :)

Working in parallel on the participant consent form made me be aware that these pieces of "communication"  are ultimately parts of the same engagement package to the prospect, therefore we probably need a light-weight consistency effort. Here are some suggestions:

**Guidelines:**
- "Give a date range or time frame that you’d like to do the interview in." - we could use a word "study" instead of the "interview" for this bullet to be applicable to a broader range of methods (user testing, contextual inquiries, surveys, etc. )

**No Referral template:**
- Let's add a greeting :)

**Overall:**
- Let's try to stay away from the words like "some", "just", 
- Do we want to use [Organization] or [Agency]? Ether one works, just need to consolidate

**Comment by pglevy** [comment]
This is looking great, @katharine-carr. A few thoughts and questions for both you (@Bixal/methods):

1. For the placeholder text, do you have thoughts on something to use besides those brackets? Just trying to think about what's the best thing to use given the intention is for people to copy and paste this into an email editor. (So we don't want extra formatting they'd have to remove, but I feel the like brackets, with their thin and vertical shape, might be slightly harder to select with the mouse than other options.)
2. Agree on the need for something more generic than "interview." "Study" may also have some academic connotation, but that could work if we want to stick with that. What about "activity"? Too generic?
3. I lean towards "organization" over "agency" since it has broader application. (Some of our clients are "departments." USAID uses "bureaus" for some things.)
4. Agree on avoiding "some" and "just" but I didn't see that in this draft. I think things like "some period of time" for placeholder text is OK because it reads like a real sentence.

![sam](https://user-images.githubusercontent.com/5177337/107047357-b9cdea80-6795-11eb-8ce6-3e9b3d431ae3.gif)

**Comment by katharine-carr** [comment]
Hello again! @pglevy @sofya-UX Here is updated guidance and templates for your review.

**Updates:** 
Text edits to Guidance. Added a note about mentioning incentives.
Changed 'agency' to 'client's organization'. Does this work?
Added greeting to No Referral Template.
Added example of mentioning an incentive.
Changed 'interview' word to 'session' - this is a good, vague, multi-use word. LMK if that works for you all.
Re: formatting to make it easy to select and plop in actual text to the template -- can we do it like USDS did it? I dont know how to make that formatting >.<

### Guidance

- Be clear about who you are and what you’re trying to do. Give minimal but relevant context of what you are doing. Think in terms of how the project would help this person, and the type of information you are seeking from them.
- Be clear about what you’re asking of the recipient. Specify the research method (interview, survey, etc.) and the time investment on the participant’s side. If applicable, include information about an incentive.
- Include information about technology expectations - remote vs in person, screen-sharing component, what tool you’ll use to connect, etc. 
- Leave the end open so they can ask further questions before accepting.
- Avoid using the term ‘research’ as this can have a different connotation to audiences not in the UX research field. Instead, try ‘running a study’, ‘gathering information’ or ‘seeking to learn’.
- Avoid using jargon and any acronyms the participant might not be familiar with.
- If relevant, share the name of referring party near the beginning of the email, or in the subject line as well.
- Format the ask in a different type to draw the eye (bold, italics, etc.)


### With Referral

**Template:**
Hi [Participant name],

[Referral name] shared your contact information with me. I’m part of a team working with [client’s organization] to [achieve some goal relevant to the participant], and he mentioned you as someone who might be able to give us some feedback. We’re [performing some research method] with [audience group] to [achieve the goal of the research method].

Would you have [amount of time] to [participate in some research method] over [some time period]? [Technical logistics of the session and mention of incentives that will be offered]

I’m happy to answer further questions or schedule a time with you. Let me know if you’re interested.

Best,
[Your Name]

**Example:**
Hi Frodo,

Bilbo Baggins shared your contact information with me. I’m part of a team working with the Department of Education to improve public hobbit education, and he mentioned you as someone who might be able to give us some feedback. We’re doing a series of interviews with hobbit students to hear their experiences and learn where improvements are needed. 

Would you have about an hour to talk with us in the next week? The interview would be remote, through Microsoft Teams and have a screen-sharing component. The Department of Education can provide 100 ducats in exchange for your participation.

I’m happy to answer further questions or schedule a time with you. Let me know if you’d be interested.

Best,
Samwise


### No Referral

**Template:**
Hi [Participant name],

I’m part of a team working with [client’s organization] to [achieve some goal relevant to the participant]. We’re [performing some research method] with [audience group] to [achieve the goal of the research method].

Would you have [amount of time] to [participate in some research method] over [some time period]? [Technical logistics of the session and mention of incentives that will be offered]

I’m happy to answer further questions or schedule a time with you. Let me know if you’re interested.

Best,
[Your name]

**Example:**
Hi Frodo,

I’m part of a team working with the Department of Education to improve public hobbit education. We’re doing a series of interviews with hobbit students to hear their experiences and learn where improvements are needed. 

Would you have about an hour to talk with us in the next week? The interview would be remote, through Microsoft Teams and have a screen-sharing component. The Department of Education can provide 100 ducats in exchange for your participation.

I’m happy to answer further questions or schedule a time with you. Let me know if you’d be interested.

Best,
Samwise

**Comment by pglevy** [comment]
I think this looks good, @katharine-carr. I'll probably have a few minor copy edits for the final version, but I think the core content is there. Did you have any other feedback, @sofya-UX?

For the formatting, what 18F used is the "code" or "pre-formatted" tag. It's nice for rendering on the web page, but the problem with copying and pasting into rich text editors is that it will usually be formatted differently, requiring the user to then change the formatting.
![image](https://user-images.githubusercontent.com/5177337/107517562-e611ae80-6b7b-11eb-9e07-957dc45d7142.png)

After playing around with it more this morning, I think we might try a triple bracket. This, along with the white space helps it stand out more visually. And when you're trying to select the text for replacement, the additional brackets provide a bigger "handle" to grab with the mouse. Editors are usually smart enough to extend the selection to the leftmost bracket as long as you click anywhere in the middle of the three. Try it out and let me know what you think. Either way, don't worry about changing what you have here. I can make the change when adding to the repo.
![image](https://user-images.githubusercontent.com/5177337/107517908-5caeac00-6b7c-11eb-804a-d7db0fbb5d63.png)

**Comment by pglevy** [comment]
I'm going to go ahead and start marking up this page.

**Comment by pglevy** [comment]
It's not linked from anywhere yet, but it's [live on the site here](https://bixal.github.io/methods/introduction-message/). Made a few copyedits and some minor formatting. Let me know if you see anything amiss, @Bixal/methods.
